// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYWxiYEiqKYQIZK4O_QoK2D12Rm9WE78',
    appId: '1:733879786377:web:c513fff77ef939b2f8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    authDomain: 'learning-platform-a.firebaseapp.com',
    storageBucket: 'learning-platform-a.appspot.com',
    measurementId: 'G-YF90SMTLBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqKTMRmwRCkbHyG6EDzocA0bvtfGQQzM',
    appId: '1:733879786377:android:b17ae0485fbbecd0f8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    storageBucket: 'learning-platform-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Sa4qRX55aiYDxuMVRIOM2Hw2Tge0m_c',
    appId: '1:733879786377:ios:055b1ee19395ffb4f8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    storageBucket: 'learning-platform-a.appspot.com',
    iosClientId: '733879786377-l4e58q0tpst2q1nuhhbmlu1bf7lt4sph.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Sa4qRX55aiYDxuMVRIOM2Hw2Tge0m_c',
    appId: '1:733879786377:ios:3703ea9da27dd19bf8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    storageBucket: 'learning-platform-a.appspot.com',
    iosClientId: '733879786377-e2kivn1ce1vdg2go2nsefp7kb3akediu.apps.googleusercontent.com',
    iosBundleId: 'com.learning.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnYWxiYEiqKYQIZK4O_QoK2D12Rm9WE78',
    appId: '1:733879786377:web:5ee42182e4db625af8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    authDomain: 'learning-platform-a.firebaseapp.com',
    storageBucket: 'learning-platform-a.appspot.com',
    measurementId: 'G-R5ZBS3E1HE',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDnYWxiYEiqKYQIZK4O_QoK2D12Rm9WE78',
    appId: '1:733879786377:web:e9274d663df7678af8df58',
    messagingSenderId: '733879786377',
    projectId: 'learning-platform-a',
    authDomain: 'learning-platform-a.firebaseapp.com',
    storageBucket: 'learning-platform-a.appspot.com',
    measurementId: 'G-52YP3JVSCT',
  );
}
